wordpress:
   image: wordpress
   volumes:
   - .:/var/www/html   #montar el directorio actual de la maquina hospedadora en el /var del contenedor a crearse
   links:
   - db:mysql
   ports:
   - 8080:80
db:
   image: mariadb
   environment:
   MYSQL_ROOT_PASSWORD: password
